import React from 'react';
import Head from 'next/head';
import { groq } from 'next-sanity';
import { getClient } from '@lib/sanity';
import { Page } from '@typings/page';

const Page = ({ page }: Page) => {
  console.log(page);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl">{page.title}</h1>
    </div>
  );
};

export default Page;

export const getStaticPaths = async () => {
  const query = groq`
    *[_type == "page"]{
      _id,
      slug {
        current
      }
    }
  `;

  const pages = await getClient().fetch(query);
  const paths = pages.map((page) => ({
    params: {
      slug: page.slug.current,
    },
  }));
  return {
    paths,
    fallback: 'blocking',
  };
};

export const getStaticProps = async ({ params }) => {
  const query = groq`
    *[_type == "page" && slug.current == $slug][0]{
      title,
      slug {
        current
      },
      _id,
      excerpt,
      keywords
    }
  `;
  const pagesQuery = groq`
    *[_type == "page" && title != "Home"] | order(menuPosition asc) {
      ...
      
    }
  `;

  const page = await getClient().fetch(query, {
    slug: params.slug,
  });

  const pages = await getClient().fetch(pagesQuery);

  if (!page) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      page,
      pages,
    },
    revalidate: 60,
  };
};
