import Head from 'next/head';
import { getClient } from '@lib/sanity';
import { groq } from 'next-sanity';
import { GetStaticProps } from 'next';
import type { Page } from '@typings/page';
import Image from 'next/image';
import ContentWrapper from '@components/ContentWrapper/ContentWrapper';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export default function Home({ page, pages, pageContent }: Page) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContentWrapper content={pageContent} />
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const pageQuery = groq`
  *[_type == "page" && title == "Home"] {
    title,
    slug {
      current
    },
    _id,
    excerpt,
    keywords,
    contentBlocks[] -> {...} 
  }
  `;

  const pagesQuery = groq`
  *[_type == "page" && title != "Home"] | order(menuPosition asc) {
    _id,
    title,
    slug {
      current
    }
  }
  `;

  const page = await getClient().fetch(pageQuery);
  const pages = await getClient().fetch(pagesQuery);

  return {
    props: {
      page: page[0],
      pages,
      pageContent: page[0].contentBlocks,
    },
    revalidate: 10,
  };
};
