import Head from 'next/head';
import { getClient, usePreviewSubscription } from '@lib/sanity';
import { groq } from 'next-sanity';
import { GetStaticProps } from 'next';
import type { HomePage } from 'typings/homePage';

export default function Home(props: HomePage) {
  console.log(props);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-7xl text-red-500 mx-5">Hello World</h1>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const pageQuery = groq`
  *[_type == "homePage"] {
    ...
  }
  `;

  const page = await getClient().fetch(pageQuery);

  return {
    props: {
      page,
    },
    revalidate: 10,
  };
};
